Add Deno support
beabee-communityrm/beabee-common pull request #2
Opened 2024-01-17 14:42 UTC by JumpLink

2024-01-18 14:42 UTC, wpf500 reviewed
Ah nice one, good to get this library updated etc.

Do we really need the tests in Deno and Node? I guess we could just keep one?

2024-01-18 16:13 UTC, JumpLink commented
> Ah nice one, good to get this library updated etc.
> 
> Do we really need the tests in Deno and Node? I guess we could just keep one?

Yes we can just keep one, in this case I would keep the Deno tests because testing is a feature of Deno and we could save jest as an additional dependency. Then I just write a simple test that checks if the types for Node.js are correct to make sure that the same dependencies are used

2024-01-18 17:02 UTC, wpf500 commented
Sounds good to me :+1:

2024-01-18 19:56 UTC, JumpLink commented
if we use Deno for the tests we can also use the formatter of Deno to save another dependency to prettier

2024-01-19 11:21 UTC, wpf500 requested changes
Thanks for doing so much clearing up of my tangled code! I'd really like to do some more thinking about how to structure this library at some point but this is a great start! :tada:

2024-01-19 11:21 UTC, wpf500 commented on src/types/rule-pperator-params.ts
Typo in file name, should be `rule-operator-param.ts`

2024-01-19 11:51 UTC, JumpLink commented
@wpf500 Thank you! I'm now done with my changes in the PR :)

2024-01-19 11:54 UTC, merged